name: Verify submodules

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Validate submodule sync
        shell: bash
        run: |
          set -euo pipefail
          # Show submodule status
          git submodule status --recursive || true
          # Fail if any submodule shows '-' (not initialized) or '+' (modified)
          if git submodule status --recursive | grep -E '^[+-]'; then
            echo "Submodules not initialized or have local modifications"
            exit 1
          fi

      - name: Optional smoke
        shell: bash
        run: |
          test -f keymotion-trainer/package.json

  test-keymotion-trainer:
    name: Test keymotion-trainer
    needs: verify-submodules
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'keymotion-trainer/package-lock.json'

      - name: Install dependencies
        working-directory: keymotion-trainer
        run: npm ci --no-audit --no-fund

      - name: Run tests (Ubuntu headless)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: keymotion-trainer
        run: xvfb-run -a npm test --silent

      - name: Run tests (Windows/macOS)
        if: ${{ matrix.os != 'ubuntu-latest' }}
        working-directory: keymotion-trainer
        run: npm test --silent
