name: Verify submodules

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Validate submodule sync
        shell: bash
        run: |
          set -euo pipefail
          # Ensure submodule exists
          if [ ! -d "keymotion-trainer" ]; then
            echo "Submodule directory missing" >&2
            exit 1
          fi
          # Show status and fail if not initialized or modified
          git submodule status --recursive
          if git submodule status --recursive | grep -E '^[+-]'; then
            echo "Submodules not initialized or have local modifications" >&2
            exit 1
          fi

      - name: Optional smoke
        shell: bash
        run: |
          # Verify the submodule has its package.json (lightweight check)
          test -f keymotion-trainer/package.json

  test-keymotion-trainer:
    name: Test keymotion-trainer
    needs: verify-submodules
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [20]
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: keymotion-trainer/package-lock.json

      - name: Install dependencies
        working-directory: keymotion-trainer
        run: npm ci --no-audit --no-fund

      - name: Run tests (Linux headless)
        if: runner.os == 'Linux'
        working-directory: keymotion-trainer
        run: xvfb-run -a npm test --silent

      - name: Run tests (non-Linux)
        if: runner.os != 'Linux'
        working-directory: keymotion-trainer
        run: npm test --silent
