name: Verify submodules

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Init submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Validate submodule sync
        shell: bash
        run: |
          set -euo nounset
          # Ensure submodules are populated
          if [ ! -d "keymotion-trainer/.git" ] && [ ! -f "keymotion-trainer/.git" ]; then
            echo "Submodule directory missing .git; initialization failed"
            exit 1
          fi

          # Confirm git recognizes submodule is clean
          git submodule status --recursive

          # Fail if any submodule shows '-' (not initialized) or '+' (modified)
          if git submodule status --recursive | grep -E '^[+-]'; then
            echo "Submodules not initialized or have local modifications"
            exit 1
          fi

      - name: Optional smoke
        shell: bash
        run: |
          # Verify the submodule has its package.json (lightweight check)
          test -f keymotion-trainer/package.json

  test-keymotion-trainer:
    name: Test keymotion-trainer
    needs: verify-submodules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Init submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: keymotion-trainer
        run: npm ci --no-audit --no-fund

      - name: Run tests (headless)
        working-directory: keymotion-trainer
        run: xvfb-run -a npm test --silent
